### ISSUE TITLE
Radio buttons

### ISSUE THREAD

**Issue by milesify** [pdelporte/inline-edit#2]
The 'Radio button example' doesn't allow saving of a new selection in the demo but will reflect the value from '_Category_' field in the table if the page is reloaded.

**Comment by pdelporte** [comment]
Yes, it does. What it does not do, is refreshing the page to synchronise the value with "Category" as it is the same field, but presented differently. It is the same if you change the value of the "Category" the "Radio button example" is not updated, until you refresh the page. Could you give it a try again ?

**Comment by milesify** [comment]
Works as you rightly said. I have tested successfully in Firefox and in Chrome incognito, my regular Chrome must require a restart as it's still failing there. Thanks for checking!

**Comment by pdelporte** [comment]
Thanks for testing
